export const validRange = {
<<<<<<< HEAD
  SMALLINT: [0, 255],
  INT: [0, 255],
  BIGINT: [0, 255],
  VARCHAR: [0, 255],
  TEXT: [0, 255],
  DATE: [0, 255],
  DECIMAL: { before: [0, 65], after: [0, 30] },
  CHAR: [0, 255],
  FLOAT: { before: [0, 255], after: [0, 30] },
  DOUBLE: { before: [0, 255], after: [0, 30] },
  DATETIME: [0, 255],
  TIMESTAMP: [0, 255],
  BOOLEAN: [0, 1],
  TIME: [0, 255],
  YEAR: [0, 255],

  // 'BOOLEAN': ,
  // 'SERIAL': ,
  // 'DATE': ,
  // 'DATETIME': ,
  // 'TIMESTAMP': ,
  // 'TIME': ,
  // 'YEAR': ,
  // 'CHAR': ,
  // 'VARCHAR': ,
  // 'TINYTEXT': ,
  // 'TEXT': ,
  // 'MEDIUMTEXT': ,
  // 'LONGTEXT': ,
  // 'BINARY': ,
  // 'VARBINARY': ,
  // 'TINYBLOB': ,
  // 'BLOB': ,
  // 'MEDIUMBLOB': ,
  // 'LONGBLOB': ,
  // 'ENUM': ,
  // 'SET': ,
  // 'GEOMETRY': ,
  // 'POINT': ,
  // 'LINESTRING': ,
  // 'POLYGON': ,
  // 'MULTIPOINT': ,
  // 'MULTILINESTRING': ,
  // 'MULTIPOLYGON': ,
  // 'GEOMETRYCOLLECTION': ,
  // 'JSON': ,
};
=======
    'TINYINT': 4,
    'SMALLINT': 5,
    'MEDIUMINT': 9,
    'INT': [0, 255],
    'BIGINT': 20,
    'DECIMAL': {'before': [0, 255], 'after': [0, 12]},
    'FLOAT': 7,
    'DOUBLE': 20,
    'REAL': '-',
    'BIT': 64,
    'CHAR': [0, 255],
    // 'BOOLEAN': ,
    // 'SERIAL': ,
    // 'DATE': ,
    // 'DATETIME': ,
    // 'TIMESTAMP': ,
    // 'TIME': ,
    // 'YEAR': ,
    // 'CHAR': ,
    // 'VARCHAR': ,
    // 'TINYTEXT': ,
    // 'TEXT': ,
    // 'MEDIUMTEXT': ,
    // 'LONGTEXT': ,
    // 'BINARY': ,
    // 'VARBINARY': ,
    // 'TINYBLOB': ,
    // 'BLOB': ,
    // 'MEDIUMBLOB': ,
    // 'LONGBLOB': ,
    // 'ENUM': ,
    // 'SET': ,
    // 'GEOMETRY': ,
    // 'POINT': ,
    // 'LINESTRING': ,
    // 'POLYGON': ,
    // 'MULTIPOINT': ,
    // 'MULTILINESTRING': ,
    // 'MULTIPOLYGON': ,
    // 'GEOMETRYCOLLECTION': ,
    // 'JSON': ,
}
>>>>>>> 983bfe770aff4492217ee00d25256efe7160b47d
