export const validRange = {
    'TINYINT': 4,
    'SMALLINT': 5,
    'MEDIUMINT': 9,
    'INT': [0, 255],
    'BIGINT': 20,
    'DECIMAL': {'before': [0, 255], 'after': [0, 12]},
    'FLOAT': 7,
    'DOUBLE': 20,
    'REAL': '-',
    'BIT': 64,
    'CHAR': [0, 255],
    // 'BOOLEAN': ,
    // 'SERIAL': ,
    // 'DATE': ,
    // 'DATETIME': ,
    // 'TIMESTAMP': ,
    // 'TIME': ,
    // 'YEAR': ,
    // 'CHAR': ,
    // 'VARCHAR': ,
    // 'TINYTEXT': ,
    // 'TEXT': ,
    // 'MEDIUMTEXT': ,
    // 'LONGTEXT': ,
    // 'BINARY': ,
    // 'VARBINARY': ,
    // 'TINYBLOB': ,
    // 'BLOB': ,
    // 'MEDIUMBLOB': ,
    // 'LONGBLOB': ,
    // 'ENUM': ,
    // 'SET': ,
    // 'GEOMETRY': ,
    // 'POINT': ,
    // 'LINESTRING': ,
    // 'POLYGON': ,
    // 'MULTIPOINT': ,
    // 'MULTILINESTRING': ,
    // 'MULTIPOLYGON': ,
    // 'GEOMETRYCOLLECTION': ,
    // 'JSON': ,
}